menu:
    Blog: /
    Archive: /archives/
    GitHub: https://github.com/lfcyme
    About: /about/

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:
gitment: true

# Analytics
# google-analytics:
ga: 

# Copyright Infomation
startyear: 2017
