menu:
    首页: /
    归档: /archives/
    关于: /about/
    GitHub: https://github.com/lfcyme

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:
gitment: true

# Analytics
# google-analytics:
ga: 

# Copyright Infomation
startyear: 2017
