menu:
    Home: /
    Archives: /archives/
    Notes: /tags/笔记/
    About: /about/
    

favicon: /favicon.png
logo: /favicon.png

# Index information
github: lfcyme
instragram: test

# Comment
# e.g disqus: seansun
disqus: 
duoshuo:
gitment: false

# Analytics
# google-analytics:
ga: 

# Copyright Infomation
startyear: 2017
